<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>goal</string>
		<string>mod2g</string>
	</array>
	<key>name</key>
	<string>GOAL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(import)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.goal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>.$</string>
			<key>name</key>
			<string>meta.preprocessor.c.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.goal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.goal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.goal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((main|init|event)\s+)?(module)(\s+[a-z_]+)?\s*(\[((\s*[a-z]+\s*=\s*[a-z]+\s*(,(?!\])|(?=\s*\])))+)\]\s*)?{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.goal.module</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.goal.module</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.goal.module</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.goal.proplist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.goal.module</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(knowledge)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.knowledge</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.goal.section.knowledge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(beliefs)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.beliefs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*}\s$</string>
					<key>name</key>
					<string>meta.goal.section.beliefs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(goals)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.goals</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*}\s$</string>
					<key>name</key>
					<string>meta.goal.section.goals</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.prolog</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(actionspec)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.actionspec</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*}\s$</string>
					<key>name</key>
					<string>meta.goal.section.actionspecs</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)\s*(\((\s*\w+\s*(,\s*\w+\s*)*)\))?\s*{</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.actionspec.goal</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.actionspec.goal</string>
								</dict>
							</dict>
							<key>end</key>
							<string>}</string>
							<key>name</key>
							<string>meta.goal.actionspec</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>(pre|post)\s*{</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.control.goal.condition</string>
										</dict>
									</dict>
									<key>end</key>
									<string>}</string>
									<key>name</key>
									<string>meta.goal.actionspec.condition</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#comments</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#insertion</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(program)\s*\s*(\[((\s*[a-z]+\s*=\s*[a-z]+\s*(,(?!\])|(?=\s*\])))+)\]\s*)?{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.program</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.goal.proplist</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*}\s$</string>
					<key>name</key>
					<string>meta.goal.section.program</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ifs</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>end</key>
							<string>}</string>
							<key>name</key>
							<string>meta.goal.control.block</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#ifs</string>
								</dict>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%.*</string>
					<key>name</key>
					<string>comment.line.percent-sign.goal</string>
				</dict>
			</array>
		</dict>
		<key>ifs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>if</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.if.if</string>
						</dict>
					</dict>
					<key>end</key>
					<string>then</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.if.then</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.goal.control.if</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>forall</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.forall.forall</string>
						</dict>
					</dict>
					<key>end</key>
					<string>do</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.forall.do</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.goal.control.forall</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#query</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(insert|delete|send|sendonce)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.insert.goal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.goal.insertion</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#insertion</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>insertion</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>true|false</string>
					<key>name</key>
					<string>constant.language.boolean.goal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(not)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.not.goal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.goal.insertion.not</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#insertion</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.goal.predicate</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#insertion</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![A-Za-z])[a-z]\w*</string>
					<key>name</key>
					<string>string.unquoted.goal.predicate</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.goal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Z]\w+</string>
					<key>name</key>
					<string>variable.other.goal</string>
				</dict>
			</array>
		</dict>
		<key>query</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(bel)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.goal.belief</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.goal.control.belief</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#insertion</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.goal</string>
	<key>uuid</key>
	<string>4ed31fe4-dbe9-4bdc-9b86-293f6b2f1d75</string>
</dict>
</plist>
